/*
ModernTrader-Go

ModernTrader-Go

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Strategy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Strategy{}

// Strategy struct for Strategy
type Strategy struct {
	// strategyId (UUID) from DB
	StrategyId *string `json:"strategyId,omitempty"`
	// Name of Strategy
	StrategyName *string `json:"strategyName,omitempty"`
	// Tags on this Strategy
	Tags []string `json:"tags,omitempty"`
}

// NewStrategy instantiates a new Strategy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategy() *Strategy {
	this := Strategy{}
	return &this
}

// NewStrategyWithDefaults instantiates a new Strategy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategyWithDefaults() *Strategy {
	this := Strategy{}
	return &this
}

// GetStrategyId returns the StrategyId field value if set, zero value otherwise.
func (o *Strategy) GetStrategyId() string {
	if o == nil || IsNil(o.StrategyId) {
		var ret string
		return ret
	}
	return *o.StrategyId
}

// GetStrategyIdOk returns a tuple with the StrategyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Strategy) GetStrategyIdOk() (*string, bool) {
	if o == nil || IsNil(o.StrategyId) {
		return nil, false
	}
	return o.StrategyId, true
}

// HasStrategyId returns a boolean if a field has been set.
func (o *Strategy) HasStrategyId() bool {
	if o != nil && !IsNil(o.StrategyId) {
		return true
	}

	return false
}

// SetStrategyId gets a reference to the given string and assigns it to the StrategyId field.
func (o *Strategy) SetStrategyId(v string) {
	o.StrategyId = &v
}

// GetStrategyName returns the StrategyName field value if set, zero value otherwise.
func (o *Strategy) GetStrategyName() string {
	if o == nil || IsNil(o.StrategyName) {
		var ret string
		return ret
	}
	return *o.StrategyName
}

// GetStrategyNameOk returns a tuple with the StrategyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Strategy) GetStrategyNameOk() (*string, bool) {
	if o == nil || IsNil(o.StrategyName) {
		return nil, false
	}
	return o.StrategyName, true
}

// HasStrategyName returns a boolean if a field has been set.
func (o *Strategy) HasStrategyName() bool {
	if o != nil && !IsNil(o.StrategyName) {
		return true
	}

	return false
}

// SetStrategyName gets a reference to the given string and assigns it to the StrategyName field.
func (o *Strategy) SetStrategyName(v string) {
	o.StrategyName = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Strategy) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Strategy) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Strategy) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Strategy) SetTags(v []string) {
	o.Tags = v
}

func (o Strategy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Strategy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StrategyId) {
		toSerialize["strategyId"] = o.StrategyId
	}
	if !IsNil(o.StrategyName) {
		toSerialize["strategyName"] = o.StrategyName
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableStrategy struct {
	value *Strategy
	isSet bool
}

func (v NullableStrategy) Get() *Strategy {
	return v.value
}

func (v *NullableStrategy) Set(val *Strategy) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategy(val *Strategy) *NullableStrategy {
	return &NullableStrategy{value: val, isSet: true}
}

func (v NullableStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


