/* Auto generated file. Do not edit by hand. This file was generated by SchemaHero. */

CREATE TABLE broker_account_table (
                                      id INTEGER NOT NULL,
                                      user_id INTEGER NOT NULL,
                                      broker_type TEXT NOT NULL,
                                      broker_username TEXT NOT NULL,
                                      broker_password TEXT NOT NULL,
                                      active BOOLEAN NOT NULL DEFAULT TRUE,
                                      last_updated TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                      PRIMARY KEY (id)
);

create table "strategy_registry_table" ("id" integer not null, "strategy_name" text not null, "img_url" text, "active" boolean not null default 'true', "created_time" timestamp without time zone not null, "tags" text[], primary key ("id"));
create table "strategy_subscription_table" ("id" integer, "strategy_id" integer not null, "user_id" integer not null, "broker_account_id" integer not null, "active" boolean not null default 'true', "created_time" timestamp without time zone not null, "last_updated" timestamp without time zone not null, primary key ("id"), constraint strategy_subscription_table_strategy_id_fkey foreign key ("strategy_id") references "strategy_registry_table" ("id"), constraint strategy_subscription_table_broker_account_id_fkey foreign key ("broker_account_id") references "broker_account_table" ("id"));

